# Generated by Django 5.0.6 on 2024-05-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('post', '0002_alter_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='category_model',
        ),
    ]
